Repository CSC207-2022F-UofT/course-project-poppin-party-peacocks, pull requests merged in 2022-12, with the labels that each got.

#97 62 implement gui and functionality of wishlistpage
  src/main/database/users.txt
  src/main/java/Assets/addButton.png
  src/main/java/Assets/deleteButton.png
  src/main/java/Assets/refreshButton.png
  src/main/java/Assets/rightArrow.png
  src/main/java/Assets/sortButton.png
  src/main/java/Entities/Item.java
  src/main/java/Entities/Product.java
  src/main/java/Entities/ProductList.java
  src/main/java/Entities/Wishlist.java
  src/main/java/GUI/AddButton.java
  src/main/java/GUI/AddItemPage.java
  src/main/java/GUI/AddWishlistPage.java
  src/main/java/GUI/BackButton.java
  src/main/java/GUI/CustomJButton.java
  src/main/java/GUI/DeleteButton.java
  src/main/java/GUI/GradientJPanel.java
  src/main/java/GUI/ItemPanel.java
  src/main/java/GUI/ItemPanelRenderer.java
  src/main/java/GUI/RefreshButton.java
  src/main/java/GUI/RightArrowButton.java
  src/main/java/GUI/SortButton.java
  src/main/java/GUI/WishlistPage.java
Labels: enhancement

#105 62 implement gui and functionality of wishlistpage
  src/main/database/arky.txt
  src/main/java/Entities/Item.java
  src/main/java/Entities/ListOfWishlists.java
  src/main/java/Entities/Product.java
  src/main/java/Entities/ProductList.java
  src/main/java/Entities/Wishlist.java
  src/main/java/ExternalInterface/ItemUpdateChecker.java
  src/main/java/GUI/AddItemPage.java
  src/main/java/GUI/AddWishlistPage.java
  src/main/java/GUI/BackButton.java
  src/main/java/GUI/HomePage.java
  src/main/java/GUI/ItemPage.java
  src/main/java/GUI/ItemPanel.java
  src/main/java/GUI/WishlistPage.java
  src/main/java/UseCases/LoginAction.java
Labels: enhancement

#118 Update homepage gui
  src/main/java/Assets/moneySymbol.png
  src/main/java/Assets/smallerLogo.png
  src/main/java/DataBase/DataBaseParser.java
  src/main/java/GUI/HomePage.java
  src/main/java/GUI/WishlistPanel.java
Labels: enhancement

#132 Small fixes and improvements to ItemPage.
  src/main/java/Assets/price_history.jpeg
  src/main/java/GUI/ItemPage.java
Labels: documentation, improvement

#148 Added documentation for top half of GUI (A - ItemPanelRenderer)
  src/main/java/GUI/AddButton.java
  src/main/java/GUI/AddItemPage.java
  src/main/java/GUI/AddWishlistPage.java
  src/main/java/GUI/BackButton.java
  src/main/java/GUI/DeleteButton.java
  src/main/java/GUI/GradientJPanel.java
  src/main/java/GUI/HomePage.java
  src/main/java/GUI/ItemPage.java
  src/main/java/GUI/ItemPanel.java
  src/main/java/GUI/ItemPanelRenderer.java
  src/main/java/GUI/Listeners/WelcomePageActionListenerSwitchPanels.java
  src/main/java/GUI/PanelRenderer.java
  src/main/java/GUI/PriceHistoryPage.java
  src/main/java/GUI/RoundedBorder.java
Labels: documentation, improvement

#156 went through all the files and cleared all the intellij warnings
  .idea/inspectionProfiles/Project_Default.xml
  META-INF/MANIFEST.MF
  project_plan_dev.md
  src/main/database/arky.txt
  src/main/database/users.txt
  src/main/java/Entities/Item.java
  src/main/java/Entities/User.java
  src/main/java/ExternalInterface/ItemSearcher.java
  src/main/java/ExternalInterface/ItemUpdateChecker.java
  src/main/java/GUI/SortFrame.java
  src/main/java/GUI/WishlistPage.java
  src/main/java/UseCases/LoginAction/LoginAction.java
  src/main/java/UseCases/PriceHistory/PriceHistoryUseCase.java
  src/main/java/UseCases/UserRegister/UserRegisterInputs.java
  src/main/java/UseCases/UserRegister/UserRegisterResponseFormatter.java
  src/main/java/mainApp.java
  src/test/java/EntitiesTest/ItemTest.java
  src/test/java/ExternallnterfaceTest/ItemSearchTest.java
  src/test/java/UseCasesTest/PriceHistory/PriceHistoryTest.java
Labels: Codebase improvement

#168 fixed desired price not saving to wishlist and changing in GUI immediately.
  build.gradle
  src/main/database/arky.txt
  src/main/database/kevin.txt
  src/main/database/users.txt
  src/main/java/Assets/price_history.jpeg
  src/main/java/Entities/ProductList.java
  src/main/java/Entities/Wishlist.java
  src/main/java/GUI/AddItemPage.java
  src/main/java/GUI/AddWishlistPage.java
  src/main/java/GUI/HomePage.java
  src/main/java/GUI/ItemPage.java
  src/main/java/GUI/LoginPanel.java
  src/main/java/GUI/PriceHistoryPage.java
  src/main/java/GUI/SignupPanel.java
  src/main/java/GUI/WelcomePage.java
  src/main/java/GUI/WishlistPage.java
  src/main/java/GUI/WishlistPanel.java
  src/test/java/EntitiesTest/WishlistTest.java
Labels: bug
